[package]
name = "rust"
version = "0.1.0"
edition = "2021"
authors = ["angcyo@126.com"]

[dependencies]
# https://crates.io/crates/jni
# https://crates.io/crates/jni-sys
# jni绑定
jni = "0.21.1"
# https://crates.io/crates/rand
# 生成随机数
rand = "0.9.0"

[lib]
crate-type = ["cdylib"]